services:
  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: wgmi
    networks:
      - freecodecamp
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  freecodecamp:

volumes:
  postgres_data:
